### PR TITLE
Lluissalord update action

### PR DESCRIPTION
**Pull request by lluissalord**
I have made some changes in the Action class to make it more flexible and then can use it with the package that I'm doing.

I have made a description of the changes in the commits. I hope it can be helpful, probably I will continue working on it next days. I want to see what do you think about this changes and if can be merge with the master or if you are not agree with something.

### CODE REVIEW

**Comment by nlyubova** [comment]
Thank you for suggestions! Did you test it ? Does it work with MoveIt simulator and/or robot?

**Comment by lluissalord** [comment]
Yes it works on both! The part of picking I haven't test yet but I think that I haven't change anything in that part.

**Comment by nlyubova** [comment]
Great! Do you mean grasping or picking? Pick is an approximate grasping.
Just mentioned that you've decreased the tolerance and I could not grasp before with 0.01. Does it work for you?

**Comment by lluissalord** [comment]
I think I mean picking, the function pickAction is almost the same as before. The part I have changed the most is the reachAction and graspPlan.
I think I have increased from 0.01 to 0.1 the tolerance_min and using an step of 0.1 for every attempt.

**Comment by nlyubova** [comment]
Right, also about tolerance, sorry that did not see it before. Thanks for your updates! Will try it

**Pull request merged**
